export const SET_USER = 'SET_USER'

export const ADD_ACTIONS = 'ADD_ACTIONS'

export const ADD_ACTION = 'ADD_ACTION'
export const ADD_UNWATCHED = 'ADD_UNWATCHED'
export const CLEAR_UNWATCHED = 'CLEAR_UNWATCHED'

export const UPDATE_ANIMATED_ICONS = 'UPDATE_ANIMATED_ICONS'

export const SOCKET_UPDATE_GAME_CONNECTION = 'SOCKET_UPDATE_GAME_CONNECTION'
export const SOCKET_CONFIG = 'SOCKET_CONFIG'
