export const SET_MAINTENANCE = 'SET_MAINTENANCE'
export const SET_LOADED = 'SET_LOADED'

export const SET_GAMES = 'SET_GAMES'
export const SET_ACTIONS = 'SET_ACTIONS'
export const SET_DEFAULT_ACTIONS = 'SET_DEFAULT_ACTIONS'
export const SET_ACTION_DATA = 'SET_ACTION_DATA'
export const SET_BIT_PRODUCTS = 'SET_BIT_PRODUCTS'

export const REMOVE_ACTION = 'REMOVE_ACTION'
export const ADD_ACTION = 'ADD_ACTION'
export const SET_ACTION = 'SET_ACTION'

export const SET_ACTIVE_GAME = 'SET_ACTIVE_GAME'
export const SET_TRANSACTION_STATUS = 'SET_TRANSACTION_STATUS'
export const SET_SELECTED_ACTION = 'SET_SELECTED_ACTION'
export const SET_ANONYMOUS_SENDER = 'SET_ANONYMOUS_SENDER'

export const SET_DEV = 'SET_DEV'
