/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    Bits: typeof import('./src/components/Bits.vue')['default']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BNavText: typeof import('bootstrap-vue-next')['BNavText']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
